apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- if .Values.global.ingress.labels -}}
    {{-   toYaml .Values.global.ingress.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.ingress.annotations -}}
    {{-   toYaml .Values.global.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/console"
        backend:
          service:
            name: {{ .Release.Name }}-console
            port:
              number: 8082
  defaultBackend:
    service:
      {{- if eq .Values.global.ingress.defaultBackend "console" }}
      name: {{ .Release.Name }}-console
      port:
        number: 8082
      {{- else }}
      name: {{ .Release.Name }}-app
      port: 
        number: 8080
      {{- end }}