kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "weave.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weave.commonLabels" . | nindent 4 }}
    {{- include "weave.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{ include "wandb.storageClass" . | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
