apiVersion: v1
kind: Secret
metadata:
  name: wandb-api-key
  namespace: wandb
type: kubernetes.io/basic-auth
stringData:
  password: {{ required "Please set agent.apiKey to a W&B API key" .Values.agent.apiKey }}
