apiVersion: batch/v1
kind: Job
metadata:
  name: dependency-install-job
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: volcano-install-job
          image: bitnami/kubectl:latest
          command:
            - "/bin/sh"
            - "-c"
            - |
              kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: dependency-manifest-configmap
      restartPolicy: Never
