daemonset:
  install: true
  mode: "daemonset"
  presets:
    hostMetrics: true
    logsCollection: true
    kubeletMetrics: true
    kubernetesEvent: true
    kubernetesCluster: true
    statsd: true
    otlp: true
  config: {}

deployment:
  install: true
  mode: "deployment"
  presets:
    statsd: true
    otlp: true
  config: {}
