{{- $secretName := print (include "wandb.fullname" .) "-secrets" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.fullname" . }}-secrets
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
type: Opaque
# TODO: figure out a better way to support rotating
data:
{{- if $secret }}
  license: {{ $secret.data.license }}
  MYSQL_ROOT_PASSWORD: {{ $secret.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_PASSWORD: {{ $secret.data.MYSQL_PASSWORD }}
{{- else }}
  license: {{ required "license must be specified to deploy with helm" .Values.license | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 10 | b64enc }}
  MYSQL_PASSWORD: {{ default (randAlphaNum 10) .Values.mysql.password | b64enc }}
{{- end }}