nameOverride: ""
fullnameOverride: ""

mysql-exporter:
  install: true

instance:
  nameOverride: "prometheus"
  install: true
  prometheus-pushgateway:
    enabled: false
  alertmanager:
    enabled: false
