{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wandb.redis.host" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "redis.labels" . | nindent 4 }}
    {{- include "redis.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "wandb.redis.port" . }}
      protocol: TCP
      targetPort: redis
  selector:
    {{- include "redis.labels" . | nindent 4 }}
{{- end }}